//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0707NguyenTuanNghia_59131580.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SanPham
    {
        [DisplayName("Mã sản phẩm")]
        public string MaSP { get; set; }
        [DisplayName("Tên sản phẩm")]

        public string TenSP { get; set; }
        [DisplayName("Đơn vị tính")]

        public string DVT { get; set; }
        [DisplayName("Đơn giá")]

        public Nullable<decimal> DonGia { get; set; }
        [DisplayName("Xuất xứ")]

        public Nullable<bool> XuatXu { get; set; }
        [DisplayName("Nhà cung cấp")]

        public string NhaCungCap { get; set; }
        [DisplayName("Mã loại sản phẩm")]

        public string MaLSP { get; set; }
        [DisplayName("Ghi chú")]

        public string GhiChu { get; set; }
    
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
